export const productsTableData = {
  header: [
    { id: 1, title: "Name" },
    { id: 2, title: "Category" },
    { id: 3, title: "Price" },
    { id: 4, title: "Active" },
    { id: 5, title: "Action" },
  ],
};
export const ordersTableData = {
  header: [
    { id: 1, title: "ID" },
    { id: 2, title: "Reference" },
    { id: 3, title: "Customer" },
    { id: 4, title: "Total" },
    { id: 5, title: "Payment" },
    { id: 6, title: "Status" },
    { id: 7, title: "Date" },
  ],
  row: [
    {
      id: 1,
      reference: "35a4dbc6",
      customer: "Dollie Bullock",
      Total: 10,
      payment: "Credit Card",
      status: "not-paid",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 2,
      reference: "70d4d7d0",
      customer: "Dollie Bullock",
      Total: 24,
      payment: "Check",
      status: "awaiting",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 3,
      reference: "2003479c",
      customer: "Dollie Bullock",
      Total: 85,
      payment: "Bank Ware",
      status: "preparing",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 4,
      reference: "09f5443b",
      customer: "Dollie Bullock",
      Total: 83,
      payment: "Pay Pal",
      status: "error",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 5,
      reference: "35a4dbc6",
      customer: "Dollie Bullock",
      Total: 77,
      payment: "Credit Card",
      status: "delivered",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 6,
      reference: "35a4dbc6",
      customer: "Dollie Bullock",
      Total: 10,
      payment: "Credit Card",
      status: "not-paid",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 7,
      reference: "70d4d7d0",
      customer: "Dollie Bullock",
      Total: 24,
      payment: "Check",
      status: "awaiting",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 8,
      reference: "2003479c",
      customer: "Dollie Bullock",
      Total: 85,
      payment: "Bank Ware",
      status: "preparing",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 9,
      reference: "09f5443b",
      customer: "Dollie Bullock",
      Total: 83,
      payment: "Pay Pal",
      status: "error",
      date: "2015/04/10 07:03:52",
    },
    {
      id: 10,
      reference: "35a4dbc6",
      customer: "Dollie Bullock",
      Total: 77,
      payment: "Credit Card",
      status: "delivered",
      date: "2015/04/10 07:03:52",
    },
  ],
};
